### ISSUE TITLE
Migrate all uses of time_ave to time_ave_util

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOS_Util#28]
@bena-nasa has created a newer better `time_ave.x` called `time_ave_util.x` in MAPL. And I know @zhaobin74 had an issue with tripolar collections (see https://github.com/GEOS-ESM/MAPL/issues/2231) that MAPL 2.39.6 fixes.

I think the substitution should be simple but we'll probably need @sdrabenh and @Jcampbell-8 to probably exercise the postprocessing code for us.

**Comment by bena-nasa** [comment]
Just some history on this. At some point, people said, now that we are producing files on things other than LL grids, the post-processing should support it. This included time_ave.x. Now since time_ave.x used GFIO, it could not be extended to support all files we produce and keep GFIO. I decided to create a new time_ave_util.x in MAPL starting from time_ave.x, but using the modern IO system that History and ExtData use so that if they support it, the utility can use it. I felt at the time for people's comfort I would keep the old code so people could be convinced that yes this does for Lat-Lon files produce the same answer. My hope was that people would use this but probably got lost. In any case, this is what I intend to support and has all the same options (plus more) that the old time_ave.x has, so it should just be a drop-in replacement.
